services:
  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z-cpuv1
    container_name: minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Página web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    restart: always

  clickhouse:
    image: clickhouse/clickhouse-server:25.8-alpine
    container_name: clickhouse
    ports:
      - "8123:8123" # Interface HTTP
      - "8000:9000" # Interface TCP
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  clickhouse_data: